# Use an official Node.js runtime as a base image
FROM node:14-alpine as build

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the source code to the working directory
COPY . .

# Build the React app
RUN npm run build

# Use Nginx as a lightweight HTTP server
FROM nginx:alpine

# Copy the built app from the 'build' stage to the default Nginx public folder
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx when the container runs
CMD ["nginx", "-g", "daemon off;"]
